name: eco_track_whitelabel
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  domain:
    path: domain
  common:
    path: common
  flutter_riverpod: ^2.4.9
  go_router: ^14.1.1
  logger: ^2.0.2+1
  riverpod: ^2.4.9
  rxdart: ^0.27.7
  json_serializable: ^6.7.1
  json_annotation: ^4.9.0
  path_provider: ^2.1.3
  flutter_svg: ^2.0.10+1
  dio: ^5.4.3+1
  cached_network_image: ^3.3.1
  flutter_bloc: ^8.1.5
  bloc: ^8.1.4
  firebase_analytics: ^11.2.0
  firebase_core: ^3.2.0
  firebase_crashlytics: ^4.0.3
  firebase_auth: ^5.1.2
  cloud_firestore: ^5.1.0
  firebase_storage: ^12.1.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.10
  mockito: ^5.4.4

flutter:
  uses-material-design: true
  fonts:
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat-Thin.ttf
          weight: 100
        - asset: fonts/Montserrat-ExtraLight.ttf
          weight: 200
        - asset: fonts/Montserrat-Light.ttf
          weight: 300
        - asset: fonts/Montserrat-Regular.ttf
          weight: 400
        - asset: fonts/Montserrat-Medium.ttf
          weight: 500
        - asset: fonts/Montserrat-SemiBold.ttf
          weight: 600
        - asset: fonts/Montserrat-Bold.ttf
          weight: 700
        - asset: fonts/Montserrat-ExtraBold.ttf
          weight: 800
        - asset: fonts/Montserrat-Black.ttf
          weight: 900