name: cachoeira_ferreira
publish_to: 'none'
version: 0.0.1

environment:
  sdk: '>=3.4.1 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  eco_track_whitelabel:
    path: ../eco_track_whitelabel

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

dependency_overrides:
  common:
    path: common

flutter:
  uses-material-design: true
  fonts:
    - family: Inter
      fonts:
        - asset: fonts/inter/Inter-Thin.ttf
          weight: 100
        - asset: fonts/inter/Inter-ExtraLight.ttf
          weight: 200
        - asset: fonts/inter/Inter-Light.ttf
          weight: 300
        - asset: fonts/inter/Inter-Regular.ttf
          weight: 400
        - asset: fonts/inter/Inter-Medium.ttf
          weight: 500
        - asset: fonts/inter/Inter-SemiBold.ttf
          weight: 600
        - asset: fonts/inter/Inter-Bold.ttf
          weight: 700
        - asset: fonts/inter/Inter-ExtraBold.ttf
          weight: 800
        - asset: fonts/inter/Inter-Black.ttf
          weight: 900
